#Tomcat configuration
server:
  port: 9102

spring:
  application:
    name: eureka-server

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/
