#Tomcat configuration
server:
  port: 9001

spring:
  thymeleaf:
    cache: false
  jpa:
    defer-datasource-initialization: true
    show-sql: true 
  h2:
    console:
      enabled: true

#Log level configuration
logging:
  level:
    root: ERROR
    org:
      springframework:
        boot:
          autoconfigure:
            h2: INFO
          web:
            embedded:
              tomcat: INFO
    com:
      oc:
        mproducts: INFO

mes-configs:
  limitDeProduits: 3

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/